// Sample property images - in production, these would be real image URLs
// For demo purposes, we use placeholder paths that can be replaced with actual images
// Expected image structure: /properties/[property-id]/[image-name].jpg
export const allProperties = [
  {
    id: 1,
    title: "Modern 3 Bedroom Flat",
    location: "Lekki Phase 1, Lagos",
    address: "15 Admiralty Way, Lekki Phase 1, Lagos",
    price: 3500000,
    beds: 3,
    baths: 3,
    sqm: 150,
    image: "/properties/1/exterior.jpg",
    verificationStatus: "VERIFIED",
    tag: "POPULAR",
    tagColor: "bg-primary",
    description:
      "A stunning modern apartment in the heart of Lekki Phase 1. This fully serviced property offers the perfect blend of luxury and convenience, featuring contemporary finishes, spacious rooms, and premium amenities. Ideal for professionals and families looking for comfort in a prime location.",
    features: [
      "24/7 Power Supply",
      "Fully Fitted Kitchen",
      "Air Conditioning",
      "Swimming Pool",
      "Gym Access",
      "Secure Parking",
      "CCTV Security",
      "Fiber Internet Ready",
    ],
    images: [
      { id: 1, label: "Living Room", url: "/properties/1/living-room.jpg" },
      { id: 2, label: "Master Bedroom", url: "/properties/1/master-bedroom.jpg" },
      { id: 3, label: "Kitchen", url: "/properties/1/kitchen.jpg" },
      { id: 4, label: "Bathroom", url: "/properties/1/bathroom.jpg" },
      { id: 5, label: "Second Bedroom", url: "/properties/1/second-bedroom.jpg" },
      { id: 6, label: "Balcony View", url: "/properties/1/balcony.jpg" },
    ],
    landlord: {
      name: "Estate Pro Management",
      verified: true,
      listings: 15,
      responseTime: "Within 24 hours",
    },
    whistleblower: {
      name: "Chiamaka Okonkwo",
      rating: 4.8,
      reviews: 24,
      bio: "Lives in Block 5, Flat 2A - familiar with the building and can answer questions about neighborhood",
    },
  },
  {
    id: 2,
    title: "Spacious 2 Bedroom Apartment",
    location: "Wuse 2, Abuja",
    address: "Plot 42, Aminu Kano Crescent, Wuse 2, Abuja",
    price: 2800000,
    beds: 2,
    baths: 2,
    sqm: 120,
    image: "/properties/2/exterior.jpg",
    verificationStatus: "VERIFIED",
    tag: "NEW",
    tagColor: "bg-secondary",
    description:
      "A beautifully designed 2 bedroom apartment in the prestigious Wuse 2 area. Features modern architecture, quality finishes, and is located close to shopping centers, restaurants, and major business districts.",
    features: [
      "24/7 Security",
      "Backup Generator",
      "Spacious Parking",
      "Water Treatment",
      "Modern Kitchen",
      "Balcony",
    ],
    images: [
      { id: 1, label: "Living Room", url: "/properties/2/living-room.jpg" },
      { id: 2, label: "Master Bedroom", url: "/properties/2/master-bedroom.jpg" },
      { id: 3, label: "Kitchen", url: "/properties/2/kitchen.jpg" },
      { id: 4, label: "Bathroom", url: "/properties/2/bathroom.jpg" },
      { id: 5, label: "Guest Bedroom", url: "/properties/2/guest-bedroom.jpg" },
    ],
    landlord: {
      name: "Quality Homes Ltd",
      verified: true,
      listings: 20,
      responseTime: "Within 12 hours",
    },
    whistleblower: {
      name: "Adanna Smith",
      rating: 4.9,
      reviews: 18,
      bio: "Resident since 2022 - can give insights about building security, amenities, and neighborhood atmosphere",
    },
  },
  {
    id: 3,
    title: "Luxury 4 Bedroom Duplex",
    location: "Ikoyi, Lagos",
    address: "7 Bourdillon Road, Ikoyi, Lagos",
    price: 8500000,
    beds: 4,
    baths: 4,
    sqm: 300,
    image: "/properties/3/exterior.jpg",
    verificationStatus: "VERIFIED",
    tag: "PREMIUM",
    tagColor: "bg-accent",
    description:
      "An exquisite luxury duplex in the most sought-after neighborhood in Lagos. This property features premium finishes, smart home technology, a private garden, and direct access to the best schools and entertainment venues.",
    features: [
      "Smart Home System",
      "Private Garden",
      "Staff Quarters",
      "Swimming Pool",
      "Home Cinema",
      "Wine Cellar",
      "Double Garage",
      "Elevator",
    ],
    images: [
      { id: 1, label: "Grand Living Room", url: "/properties/3/living-room.jpg" },
      { id: 2, label: "Master Suite", url: "/properties/3/master-bedroom.jpg" },
      { id: 3, label: "Gourmet Kitchen", url: "/properties/3/kitchen.jpg" },
      { id: 4, label: "Spa Bathroom", url: "/properties/3/bathroom.jpg" },
      { id: 5, label: "Second Bedroom", url: "/properties/3/second-bedroom.jpg" },
      { id: 6, label: "Third Bedroom", url: "/properties/3/third-bedroom.jpg" },
      { id: 7, label: "Home Office", url: "/properties/3/office.jpg" },
      { id: 8, label: "Pool Area", url: "/properties/3/pool.jpg" },
    ],
    landlord: {
      name: "Urban Living Spaces",
      verified: true,
      listings: 8,
      responseTime: "Within 48 hours",
    },
    whistleblower: {
      name: "Chioma Ukaegbu",
      rating: 4.7,
      reviews: 31,
      bio: "Long-time resident with deep knowledge of the Ikoyi community and building amenities",
    },
  },
  {
    id: 4,
    title: "Cozy Studio Apartment",
    location: "Yaba, Lagos",
    address: "25 Herbert Macaulay Way, Yaba, Lagos",
    price: 1200000,
    beds: 1,
    baths: 1,
    sqm: 45,
    image: "/properties/4/exterior.jpg",
    verificationStatus: "PENDING",
    tag: null,
    tagColor: null,
    description:
      "A compact and efficient studio apartment perfect for young professionals. Located in the vibrant Yaba tech hub with easy access to transportation, coworking spaces, and nightlife.",
    features: [
      "Prepaid Meter",
      "Water Heater",
      "Built-in Wardrobe",
      "Tiled Floors",
      "Security Gate",
    ],
    images: [
      { id: 1, label: "Studio Space", url: "/properties/4/studio.jpg" },
      { id: 2, label: "Bedroom Area", url: "/properties/4/bedroom.jpg" },
      { id: 3, label: "Kitchenette", url: "/properties/4/kitchen.jpg" },
      { id: 4, label: "Bathroom", url: "/properties/4/bathroom.jpg" },
    ],
    landlord: {
      name: "Yaba Properties",
      verified: false,
      listings: 3,
      responseTime: "Within 48 hours",
    },
    whistleblower: {
      name: "Blessing Okafor",
      rating: 4.5,
      reviews: 12,
      bio: "Tech professional living in Yaba - can share insights about the neighborhood vibe",
    },
  },
  {
    id: 5,
    title: "Executive 3 Bedroom Flat",
    location: "Victoria Island, Lagos",
    address: "18 Adeola Odeku Street, Victoria Island, Lagos",
    price: 5500000,
    beds: 3,
    baths: 3,
    sqm: 180,
    image: "/properties/5/exterior.jpg",
    verificationStatus: "REJECTED",
    tag: "HOT",
    tagColor: "bg-destructive",
    description:
      "A premium executive apartment in the commercial heart of Lagos. Perfect for business executives with proximity to major corporate offices, embassies, and high-end restaurants.",
    features: [
      "Concierge Service",
      "Rooftop Lounge",
      "Business Center",
      "Underground Parking",
      "Gym & Spa",
      "24/7 Power",
    ],
    images: [
      { id: 1, label: "Living Room", url: "/properties/5/living-room.jpg" },
      { id: 2, label: "Master Bedroom", url: "/properties/5/master-bedroom.jpg" },
      { id: 3, label: "Kitchen", url: "/properties/5/kitchen.jpg" },
      { id: 4, label: "En-suite Bath", url: "/properties/5/bathroom.jpg" },
      { id: 5, label: "Second Bedroom", url: "/properties/5/second-bedroom.jpg" },
      { id: 6, label: "City View", url: "/properties/5/view.jpg" },
    ],
    landlord: {
      name: "Luxury Estates Nigeria",
      verified: true,
      listings: 25,
      responseTime: "Within 6 hours",
    },
    whistleblower: {
      name: "Tunde Adeyemi",
      rating: 4.6,
      reviews: 19,
      bio: "Executive living in VI - familiar with business district amenities and lifestyle",
    },
  },
  {
    id: 6,
    title: "Family 4 Bedroom Bungalow",
    location: "Gwarimpa, Abuja",
    address: "12 1st Avenue, Gwarimpa Estate, Abuja",
    price: 4200000,
    beds: 4,
    baths: 3,
    sqm: 220,
    image: "/properties/6/exterior.jpg",
    verificationStatus: "VERIFIED",
    tag: null,
    tagColor: null,
    description:
      "A spacious family bungalow in the serene Gwarimpa estate. Features a large compound, boys quarters, and is located in a child-friendly neighborhood with good schools nearby.",
    features: [
      "Large Compound",
      "Boys Quarters",
      "Garage",
      "Garden Space",
      "Borehole",
      "Prepaid Meter",
    ],
    images: [
      { id: 1, label: "Living Room", url: "/properties/6/living-room.jpg" },
      { id: 2, label: "Master Bedroom", url: "/properties/6/master-bedroom.jpg" },
      { id: 3, label: "Kitchen", url: "/properties/6/kitchen.jpg" },
      { id: 4, label: "Family Bath", url: "/properties/6/bathroom.jpg" },
      { id: 5, label: "Kids Room", url: "/properties/6/kids-room.jpg" },
      { id: 6, label: "Backyard", url: "/properties/6/backyard.jpg" },
    ],
    landlord: {
      name: "Gwarimpa Realtors",
      verified: true,
      listings: 20,
      responseTime: "Within 24 hours",
    },
    whistleblower: {
      name: "Folake Adekunle",
      rating: 4.4,
      reviews: 8,
      bio: "Family resident in Gwarimpa - can advise on schools and family-friendly amenities",
    },
  },
  {
    id: 7,
    title: "Modern 2 Bedroom Flat",
    location: "Ikeja GRA, Lagos",
    address: "8 Joel Ogunnaike Street, Ikeja GRA, Lagos",
    price: 2400000,
    beds: 2,
    baths: 2,
    sqm: 100,
    image: "/properties/7/exterior.jpg",
    verificationStatus: "VERIFIED",
    tag: "NEW",
    tagColor: "bg-secondary",
    description:
      "A newly renovated apartment in the quiet Ikeja GRA neighborhood. Close to the domestic airport and major shopping malls, perfect for frequent travelers.",
    features: [
      "Airport Proximity",
      "Shopping Access",
      "Quiet Neighborhood",
      "Modern Finishes",
      "Parking Space",
    ],
    images: [
      { id: 1, label: "Living Room", url: "/properties/7/living-room.jpg" },
      { id: 2, label: "Master Bedroom", url: "/properties/7/master-bedroom.jpg" },
      { id: 3, label: "Kitchen", url: "/properties/7/kitchen.jpg" },
      { id: 4, label: "Bathroom", url: "/properties/7/bathroom.jpg" },
      { id: 5, label: "Guest Bedroom", url: "/properties/7/guest-bedroom.jpg" },
    ],
    landlord: {
      name: "Metropolitan Properties",
      verified: true,
      listings: 30,
      responseTime: "Within 2 hours",
    },
    whistleblower: {
      name: "Zainab Hassan",
      rating: 4.9,
      reviews: 27,
      bio: "Frequent traveler living in Ikeja GRA - knows the area well and airport proximity",
    },
  },
  {
    id: 8,
    title: "Penthouse Suite",
    location: "Banana Island, Lagos",
    address: "3 Banana Island Road, Ikoyi, Lagos",
    price: 15000000,
    beds: 5,
    baths: 5,
    sqm: 400,
    image: "/properties/8/exterior.jpg",
    verificationStatus: "VERIFIED",
    tag: "LUXURY",
    tagColor: "bg-accent",
    description:
      "The ultimate in luxury living. This penthouse offers panoramic views of the Lagos lagoon, private elevator access, and world-class amenities. For the discerning few who demand nothing but the best.",
    features: [
      "Private Elevator",
      "Panoramic Views",
      "Infinity Pool",
      "Smart Home",
      "Wine Room",
      "Private Cinema",
      "Helipad Access",
      "Yacht Club Membership",
    ],
    images: [
      { id: 1, label: "Grand Salon", url: "/properties/8/living-room.jpg" },
      { id: 2, label: "Master Suite", url: "/properties/8/master-bedroom.jpg" },
      { id: 3, label: "Chef Kitchen", url: "/properties/8/kitchen.jpg" },
      { id: 4, label: "Spa Bathroom", url: "/properties/8/bathroom.jpg" },
      { id: 5, label: "Second Suite", url: "/properties/8/second-bedroom.jpg" },
      { id: 6, label: "Private Cinema", url: "/properties/8/cinema.jpg" },
      { id: 7, label: "Infinity Pool", url: "/properties/8/pool.jpg" },
      { id: 8, label: "Lagoon View", url: "/properties/8/view.jpg" },
    ],
    landlord: {
      name: "Elite Residences",
      verified: true,
      listings: 3,
      responseTime: "Within 2 hours",
    },
    whistleblower: {
      name: "Ngozi Eze",
      rating: 5,
      reviews: 312,
      bio: "Luxury lifestyle expert living in Banana Island - can provide insights about premium amenities and exclusive community",
    },
  },
];

export const propertyFilters = {
  locations: ["All Locations", "Lagos", "Abuja", "Port Harcourt"],
  priceRanges: [
    "Any Price",
    "Under ₦2M",
    "₦2M - ₦5M",
    "₦5M - ₦10M",
    "Above ₦10M",
  ],
  bedOptions: ["Any", "1", "2", "3", "4+"],
};
