/**
 * Report Generator
 * 
 * Generates security scan reports in multiple formats (JSON and Markdown).
 * Provides human-readable and machine-readable outputs for vulnerability findings.
 */

import type { ScanResult, Vulnerability } from "./types";

/**
 * Generates a JSON report from scan results
 * This is the machine-readable format for CI/CD integration
 */
export function generateJSONReport(scanResult: ScanResult): string {
  return JSON.stringify(scanResult, null, 2);
}

/**
 * Generates a markdown report from scan results
 * This is the human-readable format for developers
 */
export function generateMarkdownReport(scanResult: ScanResult): string {
  const lines: string[] = [];

  // Header
  lines.push("# Security Scan Report");
  lines.push("");
  lines.push(`**Scan Date:** ${new Date(scanResult.timestamp).toLocaleString()}`);
  lines.push(`**Scan Duration:** ${(scanResult.scanDuration / 1000).toFixed(2)}s`);
  lines.push(`**Status:** ${scanResult.status.toUpperCase()}`);
  lines.push("");

  // Scanned Components
  lines.push("## Scanned Components");
  lines.push("");
  lines.push(`- Frontend: ${scanResult.scannedComponents.frontend ? "✅" : "❌"}`);
  lines.push(`- Backend: ${scanResult.scannedComponents.backend ? "✅" : "❌"}`);
  lines.push(`- Contracts: ${scanResult.scannedComponents.contracts ? "✅" : "❌"}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(`**Total Vulnerabilities:** ${scanResult.summary.total}`);
  lines.push("");

  if (scanResult.summary.total > 0) {
    lines.push("| Severity | Count |");
    lines.push("|----------|-------|");
    lines.push(`| 🔴 Critical | ${scanResult.summary.critical} |`);
    lines.push(`| 🟠 High | ${scanResult.summary.high} |`);
    lines.push(`| 🟡 Medium | ${scanResult.summary.medium} |`);
    lines.push(`| 🟢 Low | ${scanResult.summary.low} |`);
    lines.push(`| ℹ️ Info | ${scanResult.summary.info} |`);
    lines.push("");
  }

  // Failure Reason
  if (scanResult.failureReason) {
    lines.push("## ⚠️ Scan Errors");
    lines.push("");
    lines.push(scanResult.failureReason);
    lines.push("");
  }

  // Detailed Findings
  if (scanResult.vulnerabilities.length > 0) {
    lines.push("## Detailed Findings");
    lines.push("");

    // Group by severity
    const bySeverity = {
      critical: scanResult.vulnerabilities.filter((v) => v.severity === "critical"),
      high: scanResult.vulnerabilities.filter((v) => v.severity === "high"),
      medium: scanResult.vulnerabilities.filter((v) => v.severity === "medium"),
      low: scanResult.vulnerabilities.filter((v) => v.severity === "low"),
      info: scanResult.vulnerabilities.filter((v) => v.severity === "info"),
    };

    // Critical vulnerabilities
    if (bySeverity.critical.length > 0) {
      lines.push("### 🔴 Critical Severity");
      lines.push("");
      for (const vuln of bySeverity.critical) {
        lines.push(...formatVulnerability(vuln));
      }
    }

    // High vulnerabilities
    if (bySeverity.high.length > 0) {
      lines.push("### 🟠 High Severity");
      lines.push("");
      for (const vuln of bySeverity.high) {
        lines.push(...formatVulnerability(vuln));
      }
    }

    // Medium vulnerabilities
    if (bySeverity.medium.length > 0) {
      lines.push("### 🟡 Medium Severity");
      lines.push("");
      for (const vuln of bySeverity.medium) {
        lines.push(...formatVulnerability(vuln));
      }
    }

    // Low vulnerabilities
    if (bySeverity.low.length > 0) {
      lines.push("### 🟢 Low Severity");
      lines.push("");
      for (const vuln of bySeverity.low) {
        lines.push(...formatVulnerability(vuln));
      }
    }

    // Info
    if (bySeverity.info.length > 0) {
      lines.push("### ℹ️ Informational");
      lines.push("");
      for (const vuln of bySeverity.info) {
        lines.push(...formatVulnerability(vuln));
      }
    }
  } else {
    lines.push("## ✅ No Vulnerabilities Found");
    lines.push("");
    lines.push("All security scans passed successfully. No vulnerabilities detected.");
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*Generated by Automated Security Scanner*");

  return lines.join("\n");
}

/**
 * Formats a single vulnerability for markdown output
 */
function formatVulnerability(vuln: Vulnerability): string[] {
  const lines: string[] = [];

  lines.push(`#### ${vuln.title}`);
  lines.push("");
  lines.push(`**Type:** ${vuln.source}`);

  // Location
  if (vuln.location.file) {
    lines.push(`**Location:** \`${vuln.location.file}:${vuln.location.line || "?"}\``);
  } else if (vuln.location.package) {
    lines.push(`**Package:** \`${vuln.location.package}@${vuln.location.version}\``);
  }

  // Metadata
  if (vuln.metadata.cve) {
    lines.push(`**CVE:** ${vuln.metadata.cve}`);
  }
  if (vuln.metadata.cwe) {
    lines.push(`**CWE:** ${vuln.metadata.cwe}`);
  }
  if (vuln.metadata.cvss !== undefined) {
    lines.push(`**CVSS Score:** ${vuln.metadata.cvss.toFixed(1)}`);
  }

  // Description
  lines.push("");
  lines.push(vuln.description);
  lines.push("");

  // Remediation
  lines.push(`**Remediation:** ${vuln.remediation}`);

  // Fixed version for dependencies
  if (vuln.fixedVersion) {
    lines.push(`**Fixed in:** ${vuln.fixedVersion}`);
  }

  // References
  if (vuln.metadata.references && vuln.metadata.references.length > 0) {
    lines.push("");
    lines.push("**References:**");
    for (const ref of vuln.metadata.references) {
      lines.push(`- ${ref}`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  return lines;
}

/**
 * Generates a summary comment for PR
 * This is a condensed version suitable for PR comments
 */
export function generatePRComment(scanResult: ScanResult, artifactUrl?: string): string {
  const lines: string[] = [];

  // Header with status emoji
  const statusEmoji = scanResult.status === "pass" ? "✅" : scanResult.status === "fail" ? "❌" : "⚠️";
  lines.push(`<!-- security-scan-comment -->`);
  lines.push(`## ${statusEmoji} Security Scan Results`);
  lines.push("");

  // Summary
  if (scanResult.summary.total === 0) {
    lines.push("**No vulnerabilities detected!** All security scans passed successfully.");
  } else {
    lines.push(`**${scanResult.summary.total} vulnerabilities detected**`);
    lines.push("");
    lines.push("| Severity | Count |");
    lines.push("|----------|-------|");
    if (scanResult.summary.critical > 0) {
      lines.push(`| 🔴 Critical | ${scanResult.summary.critical} |`);
    }
    if (scanResult.summary.high > 0) {
      lines.push(`| 🟠 High | ${scanResult.summary.high} |`);
    }
    if (scanResult.summary.medium > 0) {
      lines.push(`| 🟡 Medium | ${scanResult.summary.medium} |`);
    }
    if (scanResult.summary.low > 0) {
      lines.push(`| 🟢 Low | ${scanResult.summary.low} |`);
    }
    if (scanResult.summary.info > 0) {
      lines.push(`| ℹ️ Info | ${scanResult.summary.info} |`);
    }
  }

  lines.push("");

  // Status message
  if (scanResult.status === "fail") {
    lines.push("⛔ **This PR cannot be merged** due to critical or high severity vulnerabilities.");
  } else if (scanResult.status === "error") {
    lines.push("⚠️ Some security scanners encountered errors. Review the detailed report.");
  } else if (scanResult.summary.medium > 0 || scanResult.summary.low > 0) {
    lines.push("⚠️ Medium or low severity vulnerabilities detected. Review recommended but not blocking.");
  }

  lines.push("");

  // Link to detailed report
  if (artifactUrl) {
    lines.push(`📄 [View Detailed Report](${artifactUrl})`);
  } else {
    lines.push("📄 View detailed report in the workflow artifacts");
  }

  lines.push("");
  lines.push(`*Scanned at ${new Date(scanResult.timestamp).toLocaleString()}*`);

  return lines.join("\n");
}
